Grab latest

diff --git a/bin/benchmark b/bin/benchmark
--- a/bin/benchmark
+++ b/bin/benchmark
@@ -68,11 +68,23 @@ fi
 # force locale setting to C so things like date output as expected
 LC_ALL=C
 
+# stop git shell & msys2 arg manipulation (/dev/null, -F/dev/debug)
+export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL="\*"
+
 # Windows has a special NUL device instead of /dev/null
-if test -e /dev/null ; then
+if test -f NUL ; then
+    echo "INTERNAL ERROR: NUL file is in the way (delete it)"
+    exit 1
+fi
+out=`cat NUL 2>&1`
+ret=$?
+if test "x$ret" = "x0" ; then
+    export NUL=NUL
+elif test -e /dev/null ; then
     export NUL=/dev/null
 else
-    export NUL=NUL
+    echo "INTERNAL ERROR: cannot determine a suitable null device"
+    exit 1
 fi
 
 # commands that this script expects
@@ -591,9 +603,6 @@ else
     $ECHO "Using [$ELP] for ELP"
 fi
 
-# prevent git shell and msys2 from expanding -F/dev/debug
-export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL="-F/dev/debug"
-
 # sanity check: make sure $RT runs
 eval \"$RT\" -s1 -F/dev/debug \"${DB}/moss.g\" LIGHT > $NUL 2>&1
 ret=$?
@@ -608,7 +617,6 @@ fi
 
 # sanity check: make sure $CMP runs
 #eval \"$CMP\" $NUL $NUL > $NUL 2>&1
-echo $NUL
 eval \"$CMP\" $NUL $NUL
 ret=$?
 if test ! "x${ret}" = "x0" ; then
